baseURL = "https://niemniemginlong.netlify.app/"
languageCode = "vi"
title = "Niệm niệm gìn lòng"
theme = "PaperMod"
[menu]
  [[menu.main]]
    name = "Bài mới viết"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Giới thiệu"
    url = "/about/"
    weight = 2
